### ISSUE TITLE
Validate usernames with '@' signs

### ISSUE THREAD

**Issue by kmanalo** [OSC/nginx_stage#19]
We have usernames like 'jdoe@location.edu'

**Comment by nickjer** [comment]
@kmanalo after you hand-edited the regular expression to get it to work at your center, and assuming you get the cluster configuration file sorted, could you confirm that all the apps work fine with these formatted usernames.

For example:

- If home directories have the `@` symbol in their name, does the File Explorer & File Editor work?
- Can you launch the Shell app inside one of these directories?

**Comment by kmanalo** [comment]
I'll let you know how my testing goes today - most of my testing was using
a 'shortname' account without any symbols like @

But currently I'm seeing general access errors, with no obvious reports
after the initial username and password entry:

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.
However, working with regular usernames I can see the dashboard and apps
just fine.

It's probably having an affect downwind but I'm not clear where.
When you have a chance, can you take a look at this behavior?  I will give
you feedback with regular usernames first (where it works), as not all the
apps had full 100% functionality.

We are also a site using two-factor authentication.

**Comment by kmanalo** [comment]
Update: 1.5.0 appears to work better after I completely removed activejobs and recloned, I can see the attempt to use 'squeue' in the slurm.rb so this is good.  I'll continue the discussion for this in the right repo, but will report on issues related to the '@' usernames.

**Comment by nickjer** [comment]
Have you tried using the `ood-apps-installer` utility for keeping the individual apps up-to-date. More documentation can be found here:

https://osc.github.io/ood-documentation/master/installation/install-apps.html

As cloning and building each app individually can be a hassle and prone to mistakes.

**Comment by nickjer** [comment]
Also, the documentation gives an example Slurm cluster config as:

```yaml
# /etc/ood/config/clusters.d/cluster1.yml
---
v2:
  metadata:
    title: "Cluster 1"
  login:
    host: "cluster1.my_center.edu"
  job:
    adapter: "slurm"
    cluster: "cluster1"
    bin: "/path/to/slurm/bin"
```

but I forgot to update the documentation and mention there is another parameter called `conf` that is used to point to the Slurm configuration file for the given cluster. So a better cluster config would look like:

```yaml
# /etc/ood/config/clusters.d/cluster1.yml
---
v2:
  metadata:
    title: "Cluster 1"
  login:
    host: "cluster1.my_center.edu"
  job:
    adapter: "slurm"
    cluster: "cluster1"
    bin: "/path/to/slurm/bin"
    conf: "/path/to/slurm.conf"
```
