### ISSUE TITLE
Convert keys to symbols from config

### ISSUE THREAD

**Issue by nickjer** [OSC/nginx_stage#8]
Currently, the code expects the config to be in the proper format, i.e., keys should be symbols:

```yaml
app_config_path:
  :dev: '/var/lib/nginx/config/apps/%{env}/%{owner}/%{name}.conf'
  :usr: '/var/lib/nginx/config/apps/%{env}/%{owner}/%{name}.conf'
  :sys: '/var/lib/nginx/config/apps/%{env}/%{name}.conf'
```

Note the preceding colon on the keys. The code `nginx_stage` can be altered so that it auto-symbolizes those keys making the config more user-friendly:

```yaml
app_config_path:
  dev: '/var/lib/nginx/config/apps/%{env}/%{owner}/%{name}.conf'
  usr: '/var/lib/nginx/config/apps/%{env}/%{owner}/%{name}.conf'
  sys: '/var/lib/nginx/config/apps/%{env}/%{name}.conf'
```
